name: Validate

env:
  TRYPTIC_DIR: ~/.local/share/nvim/site/pack/simonmclean/start/tryptic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - name: install neovim
      run: |
        sudo apt-get update
        sudo apt install -y neovim
    - name: install neovim plugins
      run: |
        git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/plenary/start/plenary
        git clone https://github.com/nvim-tree/nvim-web-devicons ~/.local/share/nvim/site/pack/nvim-tree/start/nvim-web-devicons
        git clone https://github.com/$GITHUB_REPOSITORY $TRYPTIC_DIR
        cd $TRYPTIC_DIR
        git checkout $GITHUB_SHA
    - name: install lua-language-server
      run: |
        mkdir ~/lua-language-server
        cd ~/lua-language-server
        curl -O -J -L https://github.com/LuaLS/lua-language-server/releases/download/3.7.2/lua-language-server-3.7.2-linux-x64.tar.gz
        tar -xzf *.tar.gz
    - name: check diagnostics
      run: |
        cd $TRYPTIC_DIR
        ~/lua-language-server/bin/lua-language-server --check $TRYPTIC_DIR
        cat /home/runner/lua-language-server/log/check.json
    - name: check formatting
      run: |
        cd $TRYPTIC_DIR
        npx @johnnymorganz/stylua-bin --check .
    - name: run tests
      run: |
        cd $TRYPTIC_DIR
        ./run-tests.sh
